CREATE TABLE users (
    user_id int GENERATED ALWAYS AS IDENTITY,
    name text NOT NULL,
    player_id text NOT NULL,
    power_type text NOT NULL
);

CREATE TABLE geolocation (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coord geography(point)
);

CREATE INDEX ON geolocation USING gist(coord);

-- INSERT INTO pos(name, geog) values('toto', ST_MakePoint(48.87, 2.35));
-- SELECT * FROM pos WHERE ST_DWithin(geog, ST_MakePoint(48.82036965529907, 2.2945446673050496), 1000);
